name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clean
      run: sudo make clean
    - name: make test
      run: sudo make test
    - name: make test-start
      run: sudo make test-start
